version: '3'
services:
  proxy:
    container_name: nginx_fbk
    build: ./nginx
    hostname: testFBK
    ports:
      - 8080:80
    depends_on:
      - app
    networks:
      - front

  app:
    container_name: app_fbk
    build: .
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    hostname: app_fbk
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - front
      - back

  db:
    container_name: db_fbk
    image: postgres:12.0-alpine
    hostname: db_fbk
    env_file:
      - .env.db
    volumes:
      - db_fbk:/var/lib/postgresql/data/
    networks:
      - back
  
networks:
  front:
  back:

volumes:
  db_fbk:
